### ISSUE TITLE
[Android Bootcamp] Project 1 - Review my app

### ISSUE THREAD

**Issue by dradding** [dradding/Tip-Calc#1]
My app is complete, please review. /cc @nesquena @thecodepath

**Comment by nesquena** [comment]
:+1: Looks good overall. I have provided a detailed [Project 1 Feedback Guide here](https://gist.github.com/nesquena/2e76670cfb4e751caf95) which covers the most common issues with this submitted project. Read through the feedback guide point-by-point to determine how you could improve your submission. You should consider going back and implementing applicable feedback as well. Keep in mind that one of the most important parts of Android development is learning the correct patterns and conventions.

Hopefully this has given you a first sense of the RelativeLayout which is a very powerful layout system, probably one of the best responsive-first layout systems available across web and mobile platforms. 

The next assignment will build on top of the first concepts introduced here and will also introduce networking, api use, handling remote images and navigating between activities.
